write_gatt:
  name: Write Data into Target UUID
  description: Write Data into Target UUID
  target:
    entity:
      domain: binary_sensor
      integration: ha_ble_controller
  fields:
    target_uuid:
      name: Target UUID
      description: Target UUID
      required: true
      selector:
        text:
    data:
      name: Data
      description: Data
      required: true
      selector:
        text:
    force_reconnect:
      name: Force Reconnect
      description: Force a reconnection before writing data
      required: true
      default: false
      selector:
        boolean:
    wake_before_write:
      name: Read before Write
      description: Read before Write to wake up device
      required: true
      default: false
      selector:
        boolean:
read_gatt:
  name: Read Data from Target UUID
  description: Read Data from Target UUID
  target:
    entity:
      domain: binary_sensor
      integration: ha_ble_controller
  fields:
    target_uuid:
      name: Target UUID
      description: Target UUID
      required: true
      selector:
        text: